# Generated by Django 5.2.1 on 2025-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_age_alter_comment_id_alter_issue_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='can_data_be_shared',
            field=models.BooleanField(default=False),
        ),
    ]
